
package formulario;

import java.awt.Color;
import javax.swing.*;
import java.util.*;

public class Form3 extends javax.swing.JFrame {

    /**
     * Creates new form form1
     */
    public Form3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego");
        setBackground(new java.awt.Color(255, 204, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generala");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 110, 50));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Tira Jugador1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 512, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 366, -1, -1));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 198, 121, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("     ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 109, 52, 23));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 198, 121, 102));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 198, 121, 102));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Puntos");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 109, 116, 23));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Puntos");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 110, 100, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 366, 121, 102));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 366, 121, 102));

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 0));
        jButton2.setText("Tira Jugador2");
        jButton2.setActionCommand("");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 512, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Tiros");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Tiros");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 110, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_juego.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static String msj;
    Random rnd = new Random();
    int puntos1=0, cont=1, puntos2=0, generala=0, cont2=1, j1Vueltas=0, j2Vueltas=0;
    int count1=0,count2=0, count3=0, count4=0,count5=0, count6=0;
    int c1=0, c2=0, c3=0, c4=0, c5=0, c6=0;
    int [] dado= new int[6];
    int [] puntajeJug1 = new int[20];
    int [] puntajeJug2 = new int[20];
    int j1=0, j2=0;
    int full2=0, full3=0, fullPar=0, fullImpar=0;
    int aux1 = 0, aux2=0, aux3=0, aux4=0, aux5=0, aux6=0;
    int j2Aux1=0, j2Aux2=0, j2Aux3=0, j2Aux4=0, j2Aux5=0, j2Aux6=0;
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getContentPane().setBackground(Color.PINK);
        jLabel4.setText(Form2.jugador1);
        jLabel5.setText(Form2.jugador2);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //generala=0;
        jLabel12.setText(" "+(cont));
        cont++;
        j1++;
        
        for(int i=1;i<6;i++){
            dado[i]=rnd.nextInt(6)+1;
            
        System.out.println("dado: "+ dado[i]); 
        
        }
            
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/img/dado"+dado[1]+".png")));
        jLabel6.setIcon(new ImageIcon(getClass().getResource("/img/dado"+dado[2]+".png")));
        jLabel7.setIcon(new ImageIcon(getClass().getResource("/img/dado"+dado[3]+".png")));
        jLabel10.setIcon(new ImageIcon(getClass().getResource("/img/dado"+dado[4]+".png")));
        jLabel11.setIcon(new ImageIcon(getClass().getResource("/img/dado"+dado[5]+".png")));
       
        
        for(int i=0;i<6;i++){
            if(dado[i]==1){
                count1++;//veces q salio un dado
                switch (count1) {
                    case 2:
                        aux1 = 1*count1;
                        puntos1 += aux1;
                        full2 = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+count1);
                        break;
                    case 3:
                        puntos1 += 1;
                        full3 = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+count1);
                        break;
                    case 4:
                        puntos1 += 42;
                        System.out.println(" dado "+ dado[i]+" veces "+count1);
                        break;
                    case 5:
                        generala++;
                        System.out.println(" dado "+ dado[i]+" veces "+count1);
                        break;    
                    default:
                        break;
                }
            }
            else if(dado[i]==2){
                count2++;//veces q salio un dado
                switch (count2) {
                    case 2:
                        aux2 = 2*count2;
                        puntos1 += aux2;
                        full2 = dado[i];
                        System.out.println(" dado  "+ dado[i]+" veces "+count2);
                        break;
                    case 3:
                        puntos1 += 2;
                        full3 = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+count2);
                        break;
                    case 4:
                        puntos1 += 39;
                        System.out.println(" dado "+ dado[i]+" veces "+count2);
                        break;
                    case 5:
                        generala++;
                        System.out.println(" dado "+ dado[i]+" veces "+count2);
                        break;    
                    default:
                        break;
                }
            }
            else if(dado[i]==3){
                count3++;//veces q salio un dado
                switch (count3) {
                    case 2:
                        aux3= 3*count3;
                        puntos1 += aux3;
                        full2 = dado[i];
                        System.out.println(" dado  "+ dado[i]+" veces "+count3);
                        break;
                    case 3:
                        puntos1 += 3;
                        full3 = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+count3);
                        break;
                    case 4:
                        puntos1 += 36;
                        System.out.println(" dado "+ dado[i]+" veces "+count3);
                        break;
                    case 5:
                        generala++;
                        System.out.println(" dado "+ dado[i]+" veces "+count3);
                        break;    
                    default:
                        break;
                }
            }
            else if(dado[i]==4){
                count4++;
                switch (count4) {
                    case 2:
                        aux4 = 4*count4;
                        puntos1 += aux4;
                        full2 = dado[i];
                        System.out.println(" dado  "+ dado[i]+" veces "+count4);
                        break;
                    case 3:
                        puntos1 += 4;
                        full3 = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+count4);
                        break;
                    case 4:
                        puntos1 += 33;
                        System.out.println(" dado "+ dado[i]+" veces "+count4);
                        break;
                    case 5:
                        generala++;
                        System.out.println(" dado "+ dado[i]+" veces "+count4);
                        break;    
                    default:
                        break;
                }
            }
            else if(dado[i]==5){
                count5++;
                 switch (count5) {
                    case 2:
                       aux5=5*count5;
                        puntos1 += aux5;
                        full2 = dado[i];
                        System.out.println(" dado  "+ dado[i]+" veces "+count5);
                        break;
                    case 3:
                        puntos1 += 5;
                        full3 = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+count5);
                        break;
                    case 4:
                        puntos1 += 30;
                        System.out.println(" dado "+ dado[i]+" veces "+count5);
                        break;
                    case 5:
                        generala++;
                        System.out.println(" dado "+ dado[i]+" veces "+count5);
                        break;    
                    default:
                        break;
                }
            }
            else if(dado[i]==6){
                count6++;//veces q salio un dado
                  switch (count6) {
                    case 2:
                        aux6 = 6*count6;
                        puntos1 += aux6;
                        full2 = dado[i];
                        System.out.println(" dado  "+ dado[i]+" veces "+count6);
                        break;
                    case 3:
                        puntos1 += 6;
                        full3 = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+count6);
                        break;
                    case 4:
                        puntos1 += 27;
                        System.out.println(" dado "+ dado[i]+" veces "+count6);
                        break;
                    case 5:
                        generala++;
                        System.out.println(" dado "+ dado[i]+" veces "+count6);
                        break;    
                    default:
                        break;
                }   
            }
            if(full2!=full3 && full2!=0 && full3!=0){
                full2 = full2*2;
                full3 = full3*3;
                puntos1 -=(full2+ full3 );
                puntos1 += 35;
                System.out.println("Full");
            }
            if(count1!=count6){
                if(count2==1 && count3==1 && count4==1 && count5==1){
                    puntos1 +=20;
                    System.out.println("Escalera");
                }  
            }
            if(generala!=0){
               puntos1 +=15;
               Form4 f4 = new Form4();
               f4.setVisible(true);
               this.dispose();
               System.out.println("gano el jugador 1");
               msj = " El Ganador es: "+Form2.jugador1+" Generala!!!";
            }
          }
        
        puntajeJug1[j1-1] = puntos1;
        System.out.println("puntos jugador 1 "+ Arrays.toString(puntajeJug1));
        System.out.println("puntos "+puntos1);
        jLabel8.setText("Puntos "+puntos1);
          
          count1=0;
          count2=0;
          count3=0;
          count4=0;
          count5=0;
          count6=0; 
          full2=0;
          full3=0;
          generala=0;
          puntos1=0;
            //setVisible() true or false para hacer visibles o no ciertos elementos
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel13.setText(" "+(cont2));
        cont2++;
        j2++;
       
        for(int i=1;i<6;i++){
            dado[i]=rnd.nextInt(6)+1;
            
        System.out.println("dado "+ dado[i]); 
        
        }
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/img/dado"+dado[1]+".png")));
        jLabel6.setIcon(new ImageIcon(getClass().getResource("/img/dado"+dado[2]+".png")));
        jLabel7.setIcon(new ImageIcon(getClass().getResource("/img/dado"+dado[3]+".png")));
        jLabel10.setIcon(new ImageIcon(getClass().getResource("/img/dado"+dado[4]+".png")));
        jLabel11.setIcon(new ImageIcon(getClass().getResource("/img/dado"+dado[5]+".png")));
        
          for(int i=0;i<6;i++){
            if(dado[i]==1){
                c1++;
                switch (c1) {
                    case 2:
                        j2Aux1 = 1*c1;
                        puntos2 += j2Aux1;
                        fullPar = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+c1);
                        break;
                    case 3:
                        puntos2 += 1;
                        fullImpar = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+c1);
                        break;
                    case 4:
                        puntos2 += 42;
                        System.out.println(" dado "+ dado[i]+" veces "+c1);
                        break;
                    case 5:
                        generala++;
                        System.out.println(" dado "+ dado[i]+" veces "+c1);
                        break;    
                    default:
                        break;
                }
            }
            else if(dado[i]==2){
                c2++;
                switch (c2) {
                    case 2:
                        j2Aux2 = 2*c2;
                        puntos2 += j2Aux2;
                        fullPar = dado[i];
                        System.out.println(" dado  "+ dado[i]+" veces "+c2);
                        break;
                    case 3:
                        puntos2 += 2;
                        fullImpar = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+c2);
                        break;
                    case 4:
                        puntos2 += 39;
                        System.out.println(" dado "+ dado[i]+" veces "+c2);
                        break;
                    case 5:
                        generala++;
                        System.out.println(" dado "+ dado[i]+" veces "+c2);
                        break;    
                    default:
                        break;
                }
            }
            else if(dado[i]==3){
                c3++;
                switch (c3) {
                    case 2:
                        j2Aux3= 3*c3;
                        puntos2 += j2Aux3;
                        fullPar = dado[i];
                        System.out.println(" dado  "+ dado[i]+" veces "+c3);
                        break;
                    case 3:
                        puntos2 += 3;
                        fullImpar = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+c3);
                        break;
                    case 4:
                        puntos2 += 36;
                        System.out.println(" dado "+ dado[i]+" veces "+c3);
                        break;
                    case 5:
                        generala++;
                        System.out.println(" dado "+ dado[i]+" veces "+c3);
                        break;    
                    default:
                        break;
                }
            }
            else if(dado[i]==4){
                c4++;
                switch (c4) {
                    case 2:
                        j2Aux4 = 4*c4;
                        puntos2 += j2Aux4;
                        fullPar = dado[i];
                        System.out.println(" dado  "+ dado[i]+" veces "+c4);
                        break;
                    case 3:
                        puntos2 += 4;
                        fullImpar = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+c4);
                        break;
                    case 4:
                        puntos2 += 33;
                        System.out.println(" dado "+ dado[i]+" veces "+c4);
                        break;
                    case 5:
                        generala++;
                        System.out.println(" dado "+ dado[i]+" veces "+c4);
                        break;    
                    default:
                        break;
                }
            }
            else if(dado[i]==5){
                c5++;
                 switch (c5) {
                    case 2:
                       j2Aux5=5*c5;
                        puntos2 += j2Aux5;
                        fullPar = dado[i];
                        System.out.println(" dado  "+ dado[i]+" veces "+c5);
                        break;
                    case 3:
                        puntos2 += 5;
                        fullImpar = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+c5);
                        break;
                    case 4:
                        puntos2 += 30;
                        System.out.println(" dado "+ dado[i]+" veces "+c5);
                        break;
                    case 5:
                        generala++;
                        System.out.println(" dado "+ dado[i]+" veces "+c5);
                        break;    
                    default:
                        break;
                }
            }
            else if(dado[i]==6){
                c6++;
                  switch (c6) {
                    case 2:
                        j2Aux6 = 6*c6;
                        puntos2 += j2Aux6;
                        fullPar = dado[i];
                        System.out.println(" dado  "+ dado[i]+" veces "+c6);
                        break;
                    case 3:
                        puntos2 += 6;
                        fullImpar = dado[i];
                        System.out.println(" dado "+ dado[i]+" veces "+c6);
                        break;
                    case 4:
                        puntos2 += 27;
                        System.out.println(" dado "+ dado[i]+" veces "+c6);
                        break;
                    case 5:
                        generala++;
                        System.out.println(" dado "+ dado[i]+" veces "+c6);
                        break;    
                    default:
                        break;
                }
            }
             if(fullPar!=fullImpar && fullPar!=0 && fullImpar!=0){
                fullPar = fullPar*2;
                fullImpar = fullImpar*3;
                puntos2 -=(fullPar + fullImpar);
                puntos2 += 35;
                System.out.println("Full");
            }
            if(c1!=c6){
                if(c2==1 && c3==1 && c4==1 && c5==1){
                    puntos2 +=20;
                    System.out.println("Escalera");
                }
            }
            if(generala!=0){
               puntos2 +=15;
               Form4 f4 = new Form4();
               f4.setVisible(true);
               this.dispose();
               System.out.println("gano el jugador 1");
               msj = " El Ganador es: "+Form2.jugador2+" Generala!!!";
            }
         }
    
        puntajeJug2[j2-1] = puntos2;
        System.out.println("puntos jugador 2"+ Arrays.toString(puntajeJug2));
        System.out.println("jugador 2 puntos: "+puntos2);
        jLabel9.setText("Puntos "+puntos2);
         c1=0;
         c2=0;
         c3=0;
         c4=0;
         c5=0;
         c6=0; 
         fullPar=0;
         fullImpar=0;
         generala=0;
         puntos2=0;
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jLabel13.setText(" "+0); 
        
        while(cont>3){
            
            JOptionPane.showMessageDialog(null,"Ya tiraste tres veces");
            jButton1.setEnabled(false);
            jButton2.setEnabled(true);
            cont=1;
            j1Vueltas++;
        
        }
        
        
       
             
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
       jLabel12.setText(" "+0);
     
       
        while(cont2>3){
            JOptionPane.showMessageDialog(null,"Ya tiraste tres veces");
            jButton2.setEnabled(false);
            jButton1.setEnabled(true);
            cont2=1;
            j2Vueltas++;
        }
        
        if(j2Vueltas==5){
            Form4 f4 = new Form4();
            f4.setVisible(true);
            this.dispose();
            for (int i = 0; i <puntajeJug1.length ; i++) {
                puntos1 +=puntajeJug1[i];
            }
                
            for (int i = 0; i <puntajeJug2.length ; i++) {
                puntos2 +=puntajeJug2[i];
            }
                
            if(puntos1<puntos2){
                System.out.println("gano el jugador 2");
                msj = " El Ganador es: "+Form2.jugador2+" Puntaje: "+puntos2+" !!!";
            }else if(puntos1==puntos2){
                msj="Empate!!!";
                System.out.println("Empate");
            }else{
                System.out.println("gano el jugador 1");
                msj = " El Ganador es: "+Form2.jugador1+" Puntaje: "+puntos1+" !!!";
            }
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.out.println("soy un label clickeable ");
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form3().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
